### ISSUE TITLE
Long time no see, Wada-san 👍🏻 

### ISSUE THREAD

**Issue by kaizendev2015** [letusfly85/dotfiles#9]
**Good morning** @letusfly85-san 😄 
I am **Jovan Popovic** who worked with you at **Sharedine.me**. 👋🏻 
How are you doing these days? 🙇🏻‍♂️ 
How is your family? 👪 
I hope all is well on your side. 🙏🏻

**Comment by kaizendev2015** [comment]
Hi @letusfly85-san
Please message me on skype when you are free.
live:.cid.de960e84d475f4a4
Thanks :)

**Comment by letusfly85** [comment]
@sagadev2015 

Thank you for contact!

I'm fine and our family also happy.

Now I'm coding.
How are you?

**Comment by kaizendev2015** [comment]
@letusfly85 
Thank you for your reply.

I am happy to hear that you and your family are happy.

**Comment by kaizendev2015** [comment]
@letusfly85 
I am good also. 👍🏻

**Comment by kaizendev2015** [comment]
@letusfly85 

By the way, could you tell me what kind of communication tool are you using?

Discord or telegram or Skype or Line or Slack?

**Comment by kaizendev2015** [comment]
> @sagadev2015
> 
> Thank you for contact!
> 
> I'm fine and our family also happy.
> 
> Now I'm coding. How are you?

@letusfly85 
Please reply when you are free.... 😄 😄

**Comment by letusfly85** [comment]
@sagadev2015 

> By the way, could you tell me what kind of communication tool are you using?

sorry, too late.
I'm using twitter @letusfly85 usually 👍🏻 

After you connect me on X(Twitter), I will close this issue. Thank you.

**Comment by kaizendev2015** [comment]
@letusfly85 
Sorry for my being late.
I don't like Twitter...
Could we use slack if you don't mind?
Please invite me jovan.popovic0922@gmail.com.
Thank you

**Comment by letusfly85** [comment]
@sagadev2015 

Sorry, for us slack is the business sensitive place.
Please create a twitter account 🙏🏻

**Comment by kaizendev2015** [comment]
@letusfly85 
I see.
If so, can we chat by email?

**Comment by kaizendev2015** [comment]
@letusfly85 
Please let me know your most widely-using personal email.
My email is jovan.popovic0922@gmail.com.
よろしくお願いいたします。🙏🏻🙏🏻🙏🏻

**Comment by kaizendev2015** [comment]
@letusfly85 
Google Chat seems okay...

**Comment by kaizendev2015** [comment]
@letusfly85 
Good morning 🙂 
It would be happy for me to meet you via Google meeting.
Could you tell me your available timeslots?
Thank you

**Comment by kaizendev2015** [comment]
@letusfly85 
Good afternoon 👍🏻 
How are you doing?
Could you introduce me a project? I am free and looking for a new project.
Please help me with your kind mind.🙏🏻 🙏🏻 🙏🏻 
Looking forward to hearing from you

**Comment by letusfly85** [comment]
I sent you an email 👍🏻 
I'll close this issue.
